"""add unique primariy key for URLdata table and use task id as foreight key'


Revision ID: 2d0acd632f29
Revises: 566fc26b3866
Create Date: 2023-05-19 17:34:14.978429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0acd632f29'
down_revision = '566fc26b3866'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_data', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_data', 'id')
    # ### end Alembic commands ###
