"""Added pdfs column

Revision ID: 566fc26b3866
Revises: 
Create Date: 2023-05-19 17:09:41.073012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566fc26b3866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_data', sa.Column('pdfs', sa.String(), nullable=True))
    op.add_column('url_data', sa.Column('additional_links', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_data', 'additional_links')
    op.drop_column('url_data', 'pdfs')
    # ### end Alembic commands ###
